import type { PiMemSelection } from "../../../model/evidence.js";
import type { CreatePiMemToolsOptions, FinishToolDetails, PiMemTools } from "./contracts.js";
import { CompactFinishParameters, FinishParameters } from "./schemas.js";
import { compactPreview } from "../../../../util.js";

export function createFinishTool(
  options: CreatePiMemToolsOptions,
): PiMemTools["finish"] {
  const compact = options.interfaceMode === "compact";
  return {
    name: "finish",
    label: "Finish",
    description: compact
      ? "Finish retrieval. Use sufficient only when the exact sources already read cover every fact needed by the question."
      : "Stop retrieval and commit every exact source returned by read. The " +
        "harness generates citations, hashes, provenance, deduplication, and formatting. " +
        "Call this alone, only after observing the latest search or read result in " +
        "an earlier assistant turn.",
    parameters: (compact
      ? CompactFinishParameters
      : FinishParameters) as PiMemTools["finish"]["parameters"],
    executionMode: "sequential",
    async execute(_toolCallId, params) {
      const evidence = options.ledger.inspectedEvidence;
      if (params.status === "sufficient" && evidence.length === 0) {
        throw new Error(
          "Finish rejected: sufficient retrieval requires at least one exact " +
            "source returned by read.",
        );
      }
      const evidenceSummary = params.evidenceSummary?.trim();
      const submitted: PiMemSelection = {
        status: params.status,
        citations: evidence.map((source) => ({
          memoryId: source.memoryId,
          supports: compactPreview(source.content, 360),
        })),
        ...(evidenceSummary ? { evidenceSummary } : {}),
      };
      await options.beforeFinish?.(submitted);
      const selection = options.ledger.finish(submitted);
      const details: FinishToolDetails = {
        kind: "finish",
        committedEvidenceRefs: evidence.map((source) =>
          options.ledger.evidenceRef(source.memoryId)!
        ),
        committedEvidence: evidence.map((source) => ({
          memoryId: source.memoryId,
          scopeId: source.scopeId,
          sessionId: source.sessionId,
          turnIndex: source.turnIndex,
          role: source.role,
          ...(source.timestamp === undefined
            ? {}
            : { timestamp: source.timestamp }),
          contentHash: source.contentHash,
          sourceContentHash: source.sourceContentHash,
          sourceContentLength: source.sourceContentLength,
          truncated: source.truncated,
        })),
        selection,
      };
      return {
        content: [{
          type: "text",
          text: `Committed all ${String(evidence.length)} read exact source(s); ` +
            "citations, hashes, and provenance were generated by the harness.",
        }],
        details,
        terminate: true,
      };
    },
  };
}
